# Temporary cloudbuild config for hushh-webapp
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyAJ0RDWrBYF6yIDvwdyoAVO4K5QkL218Yc"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=hushh-pda.firebaseapp.com"
      - "--build-arg"
      - "NEXT_PUBLIC_FIREBASE_PROJECT_ID=hushh-pda"
      - "--build-arg"
      - "NEXT_PUBLIC_BACKEND_URL=https://consent-protocol-1006304528804.us-central1.run.app"
      - "-t"
      - "us-central1-docker.pkg.dev/hushh-pda/cloud-run-source-deploy/hushh-webapp:latest"
      - "."
images:
  - "us-central1-docker.pkg.dev/hushh-pda/cloud-run-source-deploy/hushh-webapp:latest"
timeout: "1800s"
